M48
; DRILL file {KiCad 9.99.0-unknown-3f25b36ff1~182~ubuntu22.04.1} date 2025-05-20T22:33:03+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-20T22:33:03+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.99.0-unknown-3f25b36ff1~182~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X212.294Y-86.461
X212.294Y-92.241
T2
X208.504Y-108.331
X216.004Y-108.331
M30
